version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: postgres_katalog
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: katalog_samochodow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Automatyczne załadowanie tabel i danych przy pierwszym starcie:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  postgres_data: